# Generated by Django 6.0.4 on 2026-05-07 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("documento", models.FileField(blank=True, null=True, upload_to="proyectos/")),
                (
                    "estado",
                    models.CharField(
                        choices=[("enviado", "Enviado"), ("revision", "En Revisión"), ("aprobado", "Aprobado")],
                        default="enviado",
                        max_length=20,
                    ),
                ),
                ("fecha_envio", models.DateTimeField(auto_now_add=True)),
                ("fecha_revision", models.DateTimeField(blank=True, null=True)),
                ("calificacion", models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proyectos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-fecha_envio"]},
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("texto", models.TextField()),
                ("proyecto", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comentarios", to="core.proyecto")),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-fecha"]},
        ),
    ]

